### ISSUE TITLE
Mobile view drop down is not working

### ISSUE THREAD

**Issue by hasithajayasundara** [Olivescript/mycareers-issues#10]
Mobile view drop down (menu bar) is not working and empty

**Comment by sudaraka94** [comment]
Hi @hasithajayasundara ,
Thank you for reporting the bug

**Comment by sudaraka94** [comment]
@Chevindu we have to verify whether this is a dev fault or an issue from the template

**Comment by Chevindu** [comment]
The `main-nav` div in **header.blade.php** is yielding a `'navbar'` section. (line 53)

```php
<div class="col-md-8 main-nav" style="padding-top: 10px">
        <a id="touch-menu" class="mobile-menu" href="#"><i class="fa fa-bars fa-2x"></i></a>
        @yield('navbar')
</div>
```

But `'navbar'` section in **home.blade.php** has no content. (line 3)

```php
@section('navbar')

@endSection
```

Might that be the reason? 

Plus, PhpStorm gives another alert:
![screen shot 2017-12-24 at 11 19 25 pm](https://user-images.githubusercontent.com/11093698/34328265-1a26461e-e901-11e7-9173-5d6f75646d81.png)

Still trying to get the hang of this, so not sure what needs to be done 😬

**Comment by sudaraka94** [comment]
Discussion continued in private repo
