### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by buddhishan** [Olivescript/mycareers-issues#5]
Forgot password reset eke mail eka enawa. Ethanin ehata wada na - Ricco

**Comment by ramithuh** [comment]
the issue is.. 
http://www.mycareers.lk/**www.mycareers.lk**/password/reset/0a4c806e7412e06342c64f23bb0fa9830b33266173e1b71303c6de49907f0bf5

**Comment by sudaraka94** [comment]
Hi @ramithuh and Ricco,
Thank you for reporting the bug

**Comment by sudaraka94** [comment]
Fixed in v0.6
