### ISSUE TITLE
Developer console is showing errors in some pages

### ISSUE THREAD

**Issue by hasithajayasundara** [Olivescript/mycareers-issues#9]
It's better if you can resolve the conflicts below.Don't know whether it's necessary or not but good for further developments.
![error](https://user-images.githubusercontent.com/11781930/32706041-320a5194-c840-11e7-8654-ec669761a7a2.png)

**Comment by sudaraka94** [comment]
Hi @hasithajayasundara  ,
Thank you for reporting the bug

**Comment by sudaraka94** [comment]
fixed

**Comment by sudaraka94** [comment]
Fixed in v0.5
